USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
PAGE_SIZE = 10
NAME_MAX_LENGTH = 200
MEASUREMENT_UNIT_MAX_LENGTH = 50
DISALLOWED_USERNAMES = {"me", "admin", "root", "staff", "superuser"}
