version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: eriknathann/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/backend/media/
    depends_on:
      - db
  frontend:
    image: eriknathann/foodgram_frontend
    env_file: .env
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: eriknathann/foodgram_gateway
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../static:/var/html/static/
      - media_valume:/var/html/media/
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend