volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: eriknathann/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/backend/media/
    depends_on:
      - db
  frontend:
    image: eriknathann/foodgram_frontend
    env_file: .env
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: eriknathann/foodgram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/var/html/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend