# Generated by Django 4.2.19 on 2025-03-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_tag_options_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
