# Generated by Django 4.2.19 on 2025-04-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='D:\\Dev\\foodgram\\backend\\frontend\\src\\images\\userpic-icon.jpg', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
