# Generated by Django 4.2.19 on 2025-04-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/avatars\\userpic-icon.jpg', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
